a = int(input("Digite o primeiro valor: "))
b = int(input("Digite o segundo valor: "))
c = int(input("Digite o terceiro valor: "))
d = int(input("Digite o quarto valor: "))

print( a > b)
print( c == a)
print( d != a)
print( a <= c)
print( b > c)
print( a != c)
print( d >= a)
print( d != b)
print( d < c)
print( b >= a)
